const REMOTE_HOST_NAME: string = process.env.REACT_APP_BASE_URL as string;
const REMOTE_HOST_IMAGE_URL: string = process.env.REACT_APP_IMAGE_URL as string;
const GOOGLE_CLIENT_ID: string = process.env.REACT_APP_GOOGLE_CLIENT_ID as string;
const GOOGLE_MAPS_TOKEN: string = process.env.REACT_APP_GOOGLE_MAPS_TOKEN as string;
const GOOGLE_RECAPTCHA: string = process.env.REACT_APP_GOOGLE_RECAPTCHA as string;

const APP_ENV = {
  REMOTE_HOST_NAME: REMOTE_HOST_NAME,
  REMOTE_HOST_IMAGE_URL: REMOTE_HOST_IMAGE_URL,
  GOOGLE_CLIENT_ID: GOOGLE_CLIENT_ID,
  GOOGLE_MAPS_TOKEN: GOOGLE_MAPS_TOKEN,
  GOOGLE_RECAPTCHA: GOOGLE_RECAPTCHA,
};
export { APP_ENV };
